import './globals.css'

import NavBar from './Shared/navbar';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <h1 className='myhead'>Learn coding with bhai :- https://www.youtube.com/@azadMalikRohit</h1>
        <header>
          <NavBar />
        </header>
        
        {children}
      </body>
    </html>
  )
}
